### ISSUE TITLE
Installation issue with redmine_acts_as_taggable_on

### ISSUE THREAD

**Issue by cjbush** [alexbevi/redmine_knowledgebase#188]
I have a fresh Redmine 2.3.3 stable installation on Ubuntu 13.04 x64 with Ruby 1.9.3p194 and Rails 3.2. I downloaded the current 2.x-stable branch as a zip and unzipped it into my $REDMINE_HOME/plugins directory and ran:

bundle install
rake redmine:plugins:migrate NAME=redmine_knowledgebase

All the dependencies seem to get installed correctly. It installs redmine_acts_as_taggable_on 1.0.0. However, doing the db migration gives the following error:

rake aborted!
uninitialized constant RedmineActsAsTaggableOn
/var/lib/gems/1.9.1/gems/redmine_acts_as_taggable_on-1.0.0/lib/redmine_acts_as_taggable_on/migration.rb:3:in `<top (required)>'
/var/lib/gems/1.9.1/gems/redmine_acts_as_taggable_on-1.0.0/lib/redmine_acts_as_taggable_on/initialize.rb:3:in`<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

Am I missing something obvious?

**Comment by alexbevi** [comment]
I have a fork of the redmine_acts_as_taggable_on that seems to address most of these issues (https://github.com/alexbevi/redmine_acts_as_taggable_on). Since this is an old issue, i'm closing it for now.
