### ISSUE TITLE
install problem.  A plugin is already using the "tags" or "taggings" tables

### ISSUE THREAD

**Issue by radist** [alexbevi/redmine_knowledgebase#192]
rake redmine:plugins:migrate NAME=redmine_knowledgebase
Migrating redmine_knowledgebase (Knowledgebase)...
==  CreateCategories: migrating ===============================================
-- create_table(:kb_categories)
   -> 0.0552s
==  CreateCategories: migrated (0.0560s) ======================================

==  AddParentIdToCategories: migrating ========================================
-- add_column(:kb_categories, :parent_id, :int)
   -> 0.0862s
==  AddParentIdToCategories: migrated (0.0870s) ===============================

==  CreateArticles: migrating =================================================
-- create_table(:kb_articles)
   -> 0.0065s
==  CreateArticles: migrated (0.0069s) ========================================

==  AddAuthorToArticle: migrating =============================================
-- add_column(:kb_articles, :author_id, :int, {:default=>0, :null=>false})
   -> 0.0343s
==  AddAuthorToArticle: migrated (0.0348s) ====================================

==  AddViewingTables: migrating ===============================================
==  AddViewingTables: migrated (0.0567s) ======================================

==  AddNestedSetBoundriesToCategory: migrating ================================
-- add_column(:kb_categories, :lft, :int)
   -> 0.0167s
-- add_column(:kb_categories, :rgt, :int)
   -> 0.0173s
==  AddNestedSetBoundriesToCategory: migrated (0.0350s) =======================

==  AddRatingsToArticles: migrating ===========================================
==  AddRatingsToArticles: migrated (0.0365s) ==================================

==  AddCommentsCountToArticles: migrating =====================================
-- add_column(:kb_articles, :comments_count, :int)
   -> 0.0123s
==  AddCommentsCountToArticles: migrated (0.0130s) ============================

==  AddProjectIdToArticles: migrating =========================================
-- add_column(:kb_articles, :project_id, :int, {:default=>0})
   -> 0.0187s
==  AddProjectIdToArticles: migrated (0.0192s) ================================

==  AddUpdaterToArticle: migrating ============================================
-- add_column(:kb_articles, :updater_id, :int, {:default=>0, :null=>false})
   -> 0.0260s
==  AddUpdaterToArticle: migrated (0.0265s) ===================================

==  AddTagsAndTaggings: migrating =============================================

WARNING: The plugin redmine_contacts is using 'acts-as-taggable-on',
which means that it might accidentally delete some of your data
when you uninstall it. You should badger its maintainer to switch
to https://github.com/hdgarrood/redmine_acts_as_taggable_on.

rake aborted!
An error has occurred, all later migrations canceled:

A plugin is already using the "tags" or "taggings" tables, and
the structure of the table does not match the structure expected
by redmine_knowledgebase.
/var/data/redmine/bundle/ruby/1.9.1/gems/redmine_acts_as_taggable_on-1.0.0/lib/redmine_acts_as_taggable_on/migration.rb:71:in `assert_schema_match!'
/var/data/redmine/bundle/ruby/1.9.1/gems/redmine_acts_as_taggable_on-1.0.0/lib/redmine_acts_as_taggable_on/migration.rb:59:in`ok_to_go_up?'
/var/data/redmine/bundle/ruby/1.9.1/gems/redmine_acts_as_taggable_on-1.0.0/lib/redmine_acts_as_taggable_on/migration.rb:10:in `up'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/migration.rb:410:in`block (2 levels) in migrate'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/migration.rb:410:in `block in migrate'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in`with_connection'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/migration.rb:389:in `migrate'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/migration.rb:528:in`migrate'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/migration.rb:777:in`call'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/migration.rb:777:in `ddl_transaction'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/migration.rb:719:in`block in migrate'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/migration.rb:700:in `each'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/migration.rb:700:in`migrate'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/migration.rb:570:in `up'
/var/data/redmine/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/migration.rb:551:in`migrate'
/var/data/redmine/lib/redmine/plugin.rb:452:in `migrate_plugin'
/var/data/redmine/lib/redmine/plugin.rb:424:in`migrate'
/var/data/redmine/lib/redmine/plugin.rb:435:in `migrate'
/var/data/redmine/lib/tasks/redmine.rake:74:in`block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in`<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by djfml** [comment]
thanks a lot. I met it again when i install the plugins.Now it resolves.
