### ISSUE TITLE
Disable delete attachements

### ISSUE THREAD

**Issue by nvta2** [alexbevi/redmine_knowledgebase#199]
Hi, when user with "no edit", but it also show the delete attachements.
I have check the file: _attachments.html.erb

<%= render :partial => 'attachments/links', :locals => {:attachments => @article.attachments, :options => { :deletable => User.current.logged? } } %>

Please help me how to disable delete attachments permissions.

Regards,

**Comment by robspearman** [comment]
I believe I have this fixed on #303.  I think the fix was (_attachments.html.erb):

<%= link_to_attachments @article,
:thumbnails => true,
:author => false %>

**Comment by alexbevi** [comment]
@nvta2 , as I merged @robspearman's fork, I'm closing this issue.
