### ISSUE TITLE
Article summary doesn't respect formatting, even though it shows up in preview

### ISSUE THREAD

**Issue by matthias-stone** [alexbevi/redmine_knowledgebase#259]
In an article summary textile formatting tags are respected if one clicks "preview", but are rendered as plaintext once submitted.

The behaviour here should be consistent, but ideally textile formatting would work for the summary.

Tested on Redmine 2.5.2, knowledgebase latest master (48092eee)

**Comment by robspearman** [comment]
I have a pull request where I added the summary to the article lists to make it easier to find articles.  It would be weird to either have the summary textile formatted in the lists or to have the textile markup show up as text.  So I would vote for the summary allowing plain text only.
