### ISSUE TITLE
Not working - undefined method project_id

### ISSUE THREAD

**Issue by Yumash** [alexbevi/redmine_knowledgebase#266]
Hi! I just installed the plugin, enabled the module and when i try to add an article, i have 500 error

```
Started POST "/projects/yd/knowledgebase/articles" for 5.228.54.207 at 2014-11-21 11:18:25 +0300
Processing by ArticlesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"hidden", "category_id"=>"1", "article"=>{"title"=>"test", "summary"=>"test", "content"=>"test", "tag_list"=>"test", "version_comments"=>"test"}, "commit"=>"Create", "project_id"=>"test"}
  Current user: jumashev (id=1)
Completed 500 Internal Server Error in 53.8ms

NoMethodError (undefined method `project_id=' for #<KbArticle::Version:0xdd507ac>):
  lib/plugins/acts_as_versioned/lib/acts_as_versioned.rb:379:in `block in clone_versioned_model'
  lib/plugins/acts_as_versioned/lib/acts_as_versioned.rb:378:in `each'
  lib/plugins/acts_as_versioned/lib/acts_as_versioned.rb:378:in `clone_versioned_model'
  lib/plugins/acts_as_versioned/lib/acts_as_versioned.rb:305:in `save_version_on_create'
```

**Comment by ivymicheli** [comment]
Hi all,
I've this same issue and my redmine version is 2.5.1.

Started POST "/redmine/projects/portal-paciente/knowledgebase/articles" for 127.0.0.1 at 2015-01-13 14:11:42 -0300
Processing by ArticlesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"N/5N6mBP3fHLJPgBlEu/F01uVpXrYzc7tuzUvRbqIsM=", "category_id"=>"1", "article"=>{"title"=>"teste", "summary"=>"teste", "content"=>"teste", "tag_list"=>"teste", "version_comments"=>""}, "commit"=>"Criar", "project_id"=>"portal-paciente"}
  Current user: ivymicheli (id=1)
Completed 500 Internal Server Error in 15.6ms

NoMethodError (undefined method `project_id=' for #<KbArticle::Version:0x6f78900>):
  lib/plugins/acts_as_versioned/lib/acts_as_versioned.rb:379:in `block in clone_versioned_model'
  lib/plugins/acts_as_versioned/lib/acts_as_versioned.rb:378:in `each'
  lib/plugins/acts_as_versioned/lib/acts_as_versioned.rb:378:in `clone_versioned_model'
  lib/plugins/acts_as_versioned/lib/acts_as_versioned.rb:305:in `save_version_on_create'


Can someone help me?
Regards!

**Comment by alexbevi** [comment]
Just on the off chance that this is a similar issue to what we saw with the version comments missing, can someone test the following:

1. Create a new migration (touch a file) at `/redmine_knowledgebase/db/migrate/20150113120000_add_article_versions_project_id.rb`

2. Paste the following into the new file:
``` ruby
class AddArticleVersionsProjectId < ActiveRecord::Migration
  def self.up
    add_column :kb_article_versions, :project_id, :int, default: 0 unless column_exists?(:kb_article_versions, :project_id)
  end
end
```

3. run `rake redmine:plugins:migrate`

Let me know if that works, and if so I'll commit it officially :)

**Comment by ivymicheli** [comment]
Thanks Alexbevi for the fast anwser!

I did these steps:
Migrating redmine_knowledgebase (Knowledgebase)...
==  AddArticleVersionsProjectId: migrating ====================================
-- column_exists?(:kb_article_versions, :project_id)   -> 0.0000s
-- add_column(:kb_article_versions, :project_id, :int, {:default=>0})   -> 0.0312s

 and I get a new error:

Started POST "/redmine/projects/portalpaciente-android/knowledgebase/articles" for 127.0.0.1 at 2015-01-13 15:04:17 -0300
Processing by ArticlesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"N/5N6mBP3fHLJPgBlEu/F01uVpXrYzc7tuzUvRbqIsM=", "category_id"=>"4", "article"=>{"title"=>"teste", "summary"=>"teste", "content"=>"teste", "tag_list"=>"", "version_comments"=>""}, "commit"=>"Criar", "project_id"=>"portalpaciente-android"}
  Current user: ivymicheli (id=1)
Completed 500 Internal Server Error in 46.9ms

NoMethodError (undefined method `updater_id=' for #<KbArticle::Version:0x7751988>):
  lib/plugins/acts_as_versioned/lib/acts_as_versioned.rb:379:in `block in clone_versioned_model'
  lib/plugins/acts_as_versioned/lib/acts_as_versioned.rb:378:in `each'
  lib/plugins/acts_as_versioned/lib/acts_as_versioned.rb:378:in `clone_versioned_model'
  lib/plugins/acts_as_versioned/lib/acts_as_versioned.rb:305:in `save_version_on_create'


Regards!

**Comment by ivymicheli** [comment]
Alexbevi,

As you did for de project_id, I create a  new migrate file for updater_id:

class AddArticleVersionsUpdaterId < ActiveRecord::Migration
  def self.up
    add_column :kb_article_versions, :updater_id, :int, default: 0 unless column_exists?(:kb_article_versions, :updater_id)
  end
end


And it works for me!

Thanks a lot!
Ivy

**Comment by alexbevi** [comment]
I'll add a proper fix soon. I guess for whatever reason migrations got
messed up for some users. Thanks for testing :)

**Comment by alexbevi** [comment]
Try the https://github.com/alexbevi/redmine_knowledgebase/tree/redmine-3.0-compat branch and let me know if this is still an issue

**Comment by alexbevi** [comment]
Closing as it's been a while since there was any feedback on this item
