### ISSUE TITLE
Corrupted PDF

### ISSUE THREAD

**Issue by fuksman** [alexbevi/redmine_knowledgebase#271]
Hi. When I'm trying to export any article I get corrupted PDF file: the header of article displaying over the article body. 
![2015-02-20 18-17-40 export-3 pdf 1 page](https://cloud.githubusercontent.com/assets/2526238/6288838/d6f69030-b92c-11e4-8763-7c0fd725a8f1.png)

**Comment by Heroldgray** [comment]
+1

**Comment by zhukovRoman** [comment]
I fix it by editing app/helpers/knowledgebase_helper.rb:78 from 

 pdf.RDMwriteHTMLCell(190,5,0,0,…

to 

 pdf.RDMwriteHTMLCell(190,5,5,17,…

It add margin left and top for articles content.

**Comment by alexbevi** [comment]
I've been sitting on a fix for a while now apparently. I just pushed b40970b4acc427fbd1906dbdb2655f272be8b6f9, which should address this.
