### ISSUE TITLE
provide an API (if possible) 

### ISSUE THREAD

**Issue by allan-simon** [alexbevi/redmine_knowledgebase#274]
I'm currently helping to write a CLI  client for redmine, and it would be really nice if this plugin was providing an API (even if at first only a "readonly" one)

**Comment by alexbevi** [comment]
Interesting request. I'll see what I can do :)

**Comment by allan-simon** [comment]
thank you :) don't hesitate to poke me if you need help or people to test

**Comment by lpar** [comment]
I was just wondering about this. In particular, it would be nice to have a REST endpoint to perform a search of knowledgebase articles for a project, and get the results as JSON.

**Comment by petiepooo** [comment]
+1
python-redmine (http://python-redmine.readthedocs.io/advanced/custom_resources.html) uses the REST API to interact with Redmine.  I would love to have it also be able to access the KB articles via custom resources enumeration.
