### ISSUE TITLE
Error in bundle install on acts-as-taggable-on

### ISSUE THREAD

**Issue by cheoAlejo** [alexbevi/redmine_knowledgebase#282]
When running `bundel install` I get the following error: 
```
Bundler could not find compatible versions for gem "acts-as-taggable-on":
  In Gemfile:
    redmine_acts_as_taggable_on (~> 1.0) ruby depends on
      acts-as-taggable-on (< 2.5, >= 2.3) ruby

    acts-as-taggable-on (~> 3.4.1) ruby
```

Redmine 2.6

**Comment by cheoAlejo** [comment]
I made it work.

**Comment by alexbevi** [comment]
@cheoAlejo did you just add the version of 'acts-as-taggable-on' to the gemfile and re-run bundler?

**Comment by cheoAlejo** [comment]
I unistalled the Questions & Answers plugin, aparently both plugins cant coexist. That plugin requires version 3.4.1 of acts_as_taggable_on. I uninstalled that version of the gem as well.

**Comment by cheoAlejo** [comment]
My mistake, it wasn't Questions & Answers plugin, it was this one https://github.com/Undev/redmine_tagging
