### ISSUE TITLE
Knowledgebase plugin prevents redmine activity tab from working

### ISSUE THREAD

**Issue by kdaysh** [alexbevi/redmine_knowledgebase#283]
The Activity Tab in Redmine has stopped working since we upgraded Knowledgebase plugin 3.0.7 into our redmine environment  3.0.1

Started GET "/projects/e_u/activity" for 10.33.10.54 at 2015-06-09 09:03:31 +0100
I, [2015-06-09T09:03:31.129077 #27697]  INFO -- : Processing by ActivitiesController#index as HTML
I, [2015-06-09T09:03:31.129303 #27697]  INFO -- :   Parameters: {"id"=>"e_u"}
I, [2015-06-09T09:03:31.137769 #27697]  INFO -- :   Current user: k.m (id=62)
I, [2015-06-09T09:03:31.973572 #27697]  INFO -- : Completed 500 Internal Server Error in 844ms
F, [2015-06-09T09:03:31.976880 #27697] FATAL -- : 
NoMethodError (undefined method `event_datetime' for #<Array:0x00000010feb158>):
  lib/redmine/activity/fetcher.rb:95:in `block in events'
  lib/redmine/activity/fetcher.rb:95:in `sort!'
  lib/redmine/activity/fetcher.rb:95:in `events'
  app/controllers/activities_controller.rb:43:in `index'
I, [2015-06-09T09:03:34.445701 #27697]

**Comment by alexbevi** [comment]
Try the https://github.com/alexbevi/redmine_knowledgebase/tree/redmine-3.0-compat branch and let me know if it still doesn't work

**Comment by kdaysh** [comment]
This worked thank you!

**Comment by AtheCZ** [comment]
I've same problem with master branch. When I try to install compat branch, I get this error:
The git source https://github.com/y-yoshinoya/redmine_acts_as_taggable_on is not yet checked out. Please run `bundle install` before trying to start your application.
Running "bundle install" repeatedly doesn't help. This is my environment:
Environment:
  Redmine version                2.5.2.devel
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.1.12
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_knowledgebase          3.0.7

OS Debian Jessie
