### ISSUE TITLE
Undefined method acts_as_nested_set'

### ISSUE THREAD

**Issue by cyrildubus** [alexbevi/redmine_knowledgebase#285]
Hello,

I tried to switch from 2.3.0 to 3.0.7 and I get this error when I click on a Knowledge base tab in a project :

```
Started GET "/projects/knowledge-base/knowledgebase/articles" for my.ip at 2015-06-25 20:24:19 +0200
Processing by ArticlesController#index as HTML
  Parameters: {"project_id"=>"knowledge-base"}
  Current user: my.user (id=3)
Completed 500 Internal Server Error in 163ms (ActiveRecord: 5.3ms)

NoMethodError (undefined method `acts_as_nested_set' for #<Class:0x00000007101c18>):
  vendor/bundle/ruby/1.9.1/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
```

The upgrade did went well. I dont understand why I have this error.

Here are my version info :

```
  Redmine version                3.0.3.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  4.2.1
  redmine_knowledgebase          3.0.7
```

I also tried the 3.0-compat branch, it ended with the same result.

Can you help me ?

Thx

**Comment by ruscon** [comment]
the same problem.
any solutions ?

**Comment by rnick** [comment]
Same here after upgrade to Redmine 3.1.1

**Comment by thinknot** [comment]
Same problem here, on a fresh Redmine 3.1 stack

**Comment by alexbevi** [comment]
@thinknot @rnick @ruscon @cyrildubus I've released a new version of the plugin that should better support 3.0 and up. Let me know if it works for you ;)

**Comment by ruscon** [comment]
thx, we will check :+1:

**Comment by rooofer** [comment]
bundle exec rake redmine:plugins:migrate NAME=redmine_knowledgebase RAILS_ENV=production
Migrating redmine_knowledgebase (Knowledgebase)...
== 20121030102100 AddProjectIdToCategories: migrating =========================
-- add_column(:kb_categories, :project_id, :int, {:default=>0})
   -> 0.2922s
== 20121030102100 AddProjectIdToCategories: migrated (0.2923s) ================

== 20121205100143 AddVersioning: migrating ====================================
-- add_column(:kb_articles, :version_comments, :string, {:limit=>255, :default=>""})
   -> 0.1634s
-- add_index("kb_article_versions", :kb_article_id, {:name=>:kb_article_versions_kbaid})
   -> 0.1417s
-- add_index("kb_article_versions", :updated_at, {:name=>:index_kb_article_versions_on_updated_at})
   -> 0.1050s
== 20121205100143 AddVersioning: migrated (1.5298s) ===========================

== 20130513154700 AddTagsAndTaggings: migrating ===============================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

A plugin is already using the "tags" or "taggings" tables, and
the structure of the table does not match the structure expected
by redmine_knowledgebase.
/opt/redmine-3.1.0/lib/redmine/plugin.rb:481:in `migrate_plugin'
/opt/redmine-3.1.0/lib/redmine/plugin.rb:453:in `migrate'
/opt/redmine-3.1.0/lib/redmine/plugin.rb:464:in `migrate'
/opt/redmine-3.1.0/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
RedmineActsAsTaggableOn::Migration::SchemaMismatchError: A plugin is already using the "tags" or "taggings" tables, and
the structure of the table does not match the structure expected
by redmine_knowledgebase.
/opt/redmine-3.1.0/lib/redmine/plugin.rb:481:in `migrate_plugin'
/opt/redmine-3.1.0/lib/redmine/plugin.rb:453:in `migrate'
/opt/redmine-3.1.0/lib/redmine/plugin.rb:464:in `migrate'
/opt/redmine-3.1.0/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by alexbevi** [comment]
@rooofer apparently tags continues to be the bain of this plugin's existence :/

You can always just `rm db/migrate/20130513154700_add_tags_and_taggings.rb` in the knowledgebase to force installation to continue.

I personally wish the redmine core team would just add tags as a common feature all plugins could use instead of us all having to fight against each other ...

**Comment by alexbevi** [comment]
@rooofer could you also just paste your tags and taggings table definitions from your `schema.rb`? Also, what is your current plugin list?

**Comment by rooofer** [comment]
My current plugin list:
 redmine_agile                  1.3.9
  redmine_checklists             3.1.1
  redmine_contacts               4.0.1
  redmine_contacts_invoices      4.0.0
  redmine_custom_js              0.1.0
  redmine_finance                2.0.0
  redmine_knowledgebase          3.1.0
  redmine_slack                  0.1
  redmine_tracker_accessible     0.0.2
  redmine_update_reminder        1.0.1
  unread_issues                  1.5.0

**Comment by thinknot** [comment]
@alexbevi your latest checkin w/ acts_as_taggable_on works for us, now running Redmine 3.1 in production. Thank you very much for sorting that out.
@rooofer be careful with redmine_contacts. It has db migrations that aren't aware of this plugin, and vice versa.
