### ISSUE TITLE
Restore deleted categories

### ISSUE THREAD

**Issue by jankap** [alexbevi/redmine_knowledgebase#287]
Is there a possiblity to restore accidently deleted categories? In addition there is no prompt wheter I am sure to delete a category (with all its sub categories!). This is quite unsafe.

Thank you very mich, I really like your work!
Jan

**Comment by alexbevi** [comment]
There's no restore function, but we could add a prompt (good suggestion)

**Comment by jankap** [comment]
Okay nice. 
Are the articles save simply by backupping the mysql Database or do I need to save the whole redmine folder, too?

**Comment by alexbevi** [comment]
@jankap just the mysql database would need to be backed up. Backing up your redmine folder is a good idea just so your attachments and the exact version of redmine that you were using can be re-deployed.
