### ISSUE TITLE
Projects can't be searched

### ISSUE THREAD

**Issue by Josmorsot** [alexbevi/redmine_knowledgebase#288]
Hello, I'm using Redmine-3.0.4 with redmine_knowledgebase (Brach: 3.0 compat). Today I've tried to search a project but I hava a 500 error.
![ppal](https://cloud.githubusercontent.com/assets/7818205/8692583/e2a754b8-2acf-11e5-9859-292a737c753d.png)

In log I'm getting: 

Mysql2::Error: Unknown column 'kb_articles.kb_articles.created_at' in 'order clause': SELECT DISTINCT kb_articles.created_at, `kb_articles`.`id` FROM `kb_articles` INNER JOIN `projects` ON `projects`.`id` = `kb_articles`.`project_id` WHERE (projects.status = 1 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='knowledgebase')) AND (((kb_articles.title LIKE '%Gescontrata%') OR (kb_articles.content LIKE '%Gescontrata%')))  ORDER BY `kb_articles`.`kb_articles.created_at` DESC, `kb_articles`.`id` DESC)

**Comment by duanejevon** [comment]
Seems like this is fixed in
https://github.com/alexbevi/redmine_knowledgebase/pull/286, which we are
all hoping @alexbevi is going to merge into the redmine-3.0-compat branch
soon. :-)

**Comment by alexbevi** [comment]
Merged. Thanks @duanejevon ... I missed that one ;)
