### ISSUE TITLE
fix broken redmine 3.0 compat pull request

### ISSUE THREAD

**Issue by allustin** [alexbevi/redmine_knowledgebase#291]
https://github.com/alexbevi/redmine_knowledgebase/pull/286

Seems this pull request is broke installation on redmine 3.0

the problem is about installation gem 'awesome_nested_set'

**Comment by thinknot** [comment]
Try removing the dependency for awesome_nested_set from the plugin's Gemfile, as this now is required more specfically in Redmine 3.1. Here's what my plugins/redmine_knowledgebase/Gemfile looks like:
    gem 'redmine_acts_as_taggable_on', :git => "https://github.com/y-yoshinoya/redmine_acts_as_taggable_on", :branch => "acts_as_taggable_on-3.5.0"
    gem 'ya2yaml'

**Comment by alexbevi** [comment]
@thinknot is this still necessary? I left awesome nested set in and it seems to work in 3.0-stable and 3.1-stable

**Comment by alexbevi** [comment]
@allustin the latest version of the plugin should work for you. Let me know

**Comment by thinknot** [comment]
Agreed, I don't think it is necessary to hack the knowledgebase plugin anymore.

What I was seeing: a gem version mismatch error when bundling against the debian jessie flavor of the 3.0 source. (this rev of redmine core source was specifying a version constraint which caused a conflict error, something like `gem 'awesome_nested_set', '~> 3.0.4'` IIRC.)
Upgrading to the Redmine stable 3.1.2 source, I don't see the version constraint anymore.

**Comment by allustin** [comment]
I have check install on current redmine, it is correct and works 

but i have the another problem like in #298, steps for reproduce will be in a moment
