### ISSUE TITLE
500 Internal Server Error - if DELETE category but it's have subcategory

### ISSUE THREAD

**Issue by hello2jack** [alexbevi/redmine_knowledgebase#293]
If delete category but the category have subcategory, system will not show any warning messages, and then.... this project's knowledge base will always show "500 Internal Server Error", until i delete the subcategory in DB.

**Comment by pyhalov** [comment]
Workaround:
alter table kb_articles add constraint kb_articles_category_id foreign key (category_id) references kb_categories(id) on delete cascade;
alter table kb_categories add constraint kb_categories_parent_id foreign key (parent_id) references kb_categories(id) on delete cascade;

**Comment by kurofune** [comment]
Same error occurred.
We can't use "nowledgebase" now.

**Comment by alexbevi** [comment]
Should be fixed in v3.2.0. @hello2jack @pyhalov @kurofune please have a look when you have a moment
