### ISSUE TITLE
ActionView::Template::Error (undefined method nested_set_options'

### ISSUE THREAD

**Issue by Roshan56** [alexbevi/redmine_knowledgebase#295]
Hi alexbevi,

 I have upgrade redmine 3.1.1 version but I am not able to open knowledgebase plugin. I am getting below error in httpd logs file.

Completed 500 Internal Server Error in 265ms (ActiveRecord: 19.2ms)

ActionView::Template::Error (undefined method nested_set_options' for #<#Class:0x00000008802958:0x00000008801710>): 2: <% if cats.count > 0 %> 3: <label for="category_id"><strong><%= l(:label_jump_category) %></strong></label> 4: &nbsp; 5: <%= select_tag :category_id, options_for_select([""] + nested_set_options(cats) {|i| raw("#{'&#9657;' \* i.level} #{i.title}") }), :onchange => "if (this.value != \'\') { window.location = '#{categories_path}/' + this.value; }" %> 6: <% end %> lib/redmine/sudo_mode.rb:63:insudo_mode

**Comment by ruby-adictive** [comment]
Which version of knowledgebase plugin have you integrated?

**Comment by alexbevi** [comment]
@Roshan56 I've just published a new version that should properly support 3.1. Let me know if that solves this issue

**Comment by Roshan56** [comment]
Hello Alexbevi,

Thanks for resolved issue

Thanks,
Roshan
