### ISSUE TITLE
Access to article is not restricted

### ISSUE THREAD

**Issue by pyhalov** [alexbevi/redmine_knowledgebase#302]
When I create unprivileged user, he can go to "Knowledgebase" project tab and see categories. 
Main page says that he doesn't have permission to view articles or categories. However, he can choose articles category in menu at top right corner of the page and see articles in the category or use direct links (like projects/project1/knowledgebase/articles/11

**Comment by robspearman** [comment]
Can you confirm you have removed all knowledgebase permissions for the role for this user?

I am testing on my own fork, but I can only reproduce this if I create non-sensical permission sets like can not view articles but can edit them, etc.  With no permissions at all the user can not see the tab nor view articles with a direct link.

**Comment by alexbevi** [comment]
@robspearman: @pyhalov has a patch at https://github.com/pyhalov/redmine_knowledgebase/commit/0d2808f9f89140f504e11b7772dd89528335d368. Does this look decent?

**Comment by pyhalov** [comment]
at least it works for us

**Comment by alexbevi** [comment]
@pyhalov i'll likely end up merging this when i do 3.2.1. was just looking for feedback ;)

**Comment by robspearman** [comment]
Issue should now be fixed.
