### ISSUE TITLE
Article view counts not updating

### ISSUE THREAD

**Issue by robspearman** [alexbevi/redmine_knowledgebase#304]
In the most popular articles list every article has one view.  Viewing articles as other users and from other IPs does not change the count. 

Am I missing something?

Redmine 3.2.0.

**Comment by hello2jack** [comment]
From 3.0.4, 3.0.5, 3.0.7
The article counts always is *Viewed once*

Environment:

------------ | -------------
Redmine version                3.0.7.stable
Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-linux]
Rails version                  4.2.3
Environment                    production
Database adapter               Mysql2

**Comment by alexbevi** [comment]
Should be fixed in v3.2.0. @hello2jack can you test and verify?
