### ISSUE TITLE
[Error 500] when remove the other plugin [Redmine People plugin]

### ISSUE THREAD

**Issue by hello2jack** [alexbevi/redmine_knowledgebase#309]
After i remove the plugin Redmine People plugin, Knowledge show below error message
Mysql2::Error: Table 'redmine.taggings' doesn't exist: SHOW FULL FIELDS FROM `taggings` 

![image](https://cloud.githubusercontent.com/assets/14246273/12199087/22bf99a8-b648-11e5-94ef-22077d29aa76.png)

**Comment by alexbevi** [comment]
@hello2jack this is because both plugins are using a tagging library, and removing one will purge the taggings table the other needs. This is a known issue, and sadly there's no "easy" solution yet.
