### ISSUE TITLE
FEATURE: Tag autocomplete

### ISSUE THREAD

**Issue by kostyfisik** [alexbevi/redmine_knowledgebase#313]
Another feature request: when using tagging for articles autocomplete for existing tags can be very usefull. It is quite a nice feature to simplify tag addition, that looks to be rather common in redmine plugins, e.g. good implementation can be found in Mention plugin https://github.com/arkhitech/redmine_mentions or Favorite projects plugin or https://github.com/syntacticvexation/redmine_favourite_projects

**Comment by alexbevi** [comment]
@kostyfisik that's a great idea!

**Comment by robspearman** [comment]
This feature has been added.
