### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by dbierspb** [alexbevi/redmine_knowledgebase#314]
Ran the following as outlined in the front page guide for installation:

```
git clone git://github.com/alexbevi/redmine_knowledgebase.git plugins/redmine_knowledgebase
bundle install
rake redmine:plugins:migrate NAME=redmine_knowledgebase
```

I get kicked back with the following:

```
^ 05:53 : [redmine@sapphire /var/www/vhosts/redmine.internal/public ]$> rake redmine:plugins:migrate NAME=redmine_knowledgebase RAILS_ENV=production
(in /var/www/vhosts/redmine.internal)
Plugin redmine_knowledgebase was not found.
```

I've confirmed it's there, I'm not sure why it is not being seen.  Sorry if this is a noob thing to need assistance on -- This is some of my first-time for diving into Ruby and rails apps.

```
^ 05:54 : [redmine@sapphire /var/www/vhosts/redmine.internal/public ]$> ls -l plugins/
total 4
drwxrwxr-x 10 redmine redmine 4096 Feb  4 05:44 redmine_knowledgebase
```

**Comment by ppoektos** [comment]
```
rake redmine:plugins:migrate NAME=redmine_knowledgebase
```
This command must be executed in the root redmine folder.
And it seems that your "plugin" folder with "redmine_knowledgebase" inside is under "public" folder which is wrong.
You need to be in
/var/www/vhosts/redmine.internal 
then execute
git clone git://github.com/alexbevi/redmine_knowledgebase.git plugins/redmine_knowledgebase
bundle install
rake redmine:plugins:migrate NAME=redmine_knowledgebase

**Comment by dbierspb** [comment]
Ah, awesome that worked.  I misunderstood "root" of the folder and operated under the assumption it was the root of the web-accessible folder (public/)

Thanks!
