### ISSUE TITLE
Internal Error when try access KB link

### ISSUE THREAD

**Issue by aleJohnny** [alexbevi/redmine_knowledgebase#316]
Hello,

I just installed the plugin and after make the steps to download, install and migrate when I try access the KB link after activate the module inside a project I always got a Internal Server Error.

My installation:

```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  redmine_knowledgebase          3.1.0
  redmine_language_change        0.1.0
```

Log when I try access the KB link inside a Project

```
Started GET "/projects/assets-servidor-e-servicos/knowledgebase/articles" for 192.168.111.229 at 2016-02-16 15:12:14 -0200
Processing by ArticlesController#index as HTML
  Parameters: {"project_id"=>"assets-servidor-e-servicos"}
  Current user: amelo (id=17)
Completed 500 Internal Server Error in 99ms (ActiveRecord: 91.6ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'redmine_db.kb_categories' doesn't exist: SHOW FULL FIELDS FROM `kb_categories`):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

I tried deactivate the redmine_language_change, but didnt make any difference.

Thanks!

**Comment by kostyfisik** [comment]
Could you please provide log of runing 

bundle install
rake redmine:plugins:migrate NAME=redmine_knowledgebase

in plugin directory? It seems that there is no plugin conflict, however, the database migration was not really correct.

**Comment by abhigginbotham** [comment]
I have the same issue running 3.2 here is my trace from above

root@ubuntu:/opt/bitnami/apps/redmine/htdocs/plugins# rake redmine:plugins:migrate NAME=redmine_knowledgebase --trace
(in /opt/bitnami/apps/redmine/htdocs)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:87:in `connect'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:87:in `initialize'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/opt/bitnami/ruby/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/opt/bitnami/ruby/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:87:in `connection'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/model_schema.rb:230:in `table_exists?'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/primary_key.rb:97:in `get_primary_key'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/primary_key.rb:85:in `reset_primary_key'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/primary_key.rb:73:in `primary_key'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/attribute_assignment.rb:15:in `attributes_protected_by_default'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:337:in `block in protected_attributes_configs'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:222:in `yield'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:222:in `protected_attributes'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:126:in `block in attr_protected'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:125:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:125:in `attr_protected'
/opt/bitnami/apps/redmine/htdocs/app/models/custom_field.rb:36:in `<class:CustomField>'
/opt/bitnami/apps/redmine/htdocs/app/models/custom_field.rb:18:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:457:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:457:in `block in load_file'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:647:in `new_constants_in'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:456:in `load_file'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:354:in `require_or_load'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/field_format.rb:87:in `field_attributes'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/field_format.rb:90:in `<class:Base>'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/field_format.rb:48:in `<module:FieldFormat>'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/field_format.rb:19:in `<module:Redmine>'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/field_format.rb:18:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/lib/redmine.rb:38:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/config/initializers/30-redmine.rb:6:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:411:in `call'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:345:in `call'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/opt/bitnami/ruby/bin/rake:23:in `load'
/opt/bitnami/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
 
my version information:
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Cvs                            1.12.13
  Git                            2.6.1
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.5.6
  redmine_knowledgebase          3.1.0

**Comment by abhigginbotham** [comment]
To solve my issue I had to modify the rake statement to add the production environment like this:

rake redmine:plugins:migrate NAME=redmine_knowledgebase **RAILS_ENV="production"**

It's working fine for me now.
