### ISSUE TITLE
When no rating to new article

### ISSUE THREAD

**Issue by barbiedrummer** [alexbevi/redmine_knowledgebase#317]
I have an error after creating new article, when i go to top level of knowlegebase.
We use redmine in russian.
Any ideas?

```
translation data {:one=>"Рейтинг: %{rating_avg}/%{rating_max} после одного голоса", :other=>"Рейтинг: %{rating_avg}/%{rating_max} после %{count} голосов"} can not be used with :count => 0 
```

```
Started GET "/redmine/projects/reshenie_office/knowledgebase/articles" for 10.0.0.5 at 2016-02-16 20:57:30 +0300
Processing by ArticlesController#index as HTML
  Parameters: {"project_id"=>"reshenie_office"}
  Current user: barabanov (id=45)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_jump_box.html.erb (4.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/_list.html.erb (4.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/_list.html.erb (2.6ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/_list.html.erb (2.8ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/index.html.erb within layouts/base (17.1ms)
Completed 500 Internal Server Error in 66ms (ActiveRecord: 6.9ms)

ActionView::Template::Error (translation data {:one=>"Р РµР№С‚РёРЅРі: %{rating_avg}/%{rating_max} РїРѕСЃР»Рµ РѕРґРЅРѕРіРѕ РіРѕР»РѕСЃР°", :other=>"Р РµР№С‚РёРЅРі: %{rating_avg}/%{rating_max} РїРѕСЃР»Рµ %{count} РіРѕР»РѕСЃРѕРІ"} can not be used with :count => 0):
    2:   <div class="article-icon <%= default_icon %>">
    3:   	<% truncate_length = 100 if local_assigns[:truncate_length].nil? %>
    4:     <%= link_to truncate(article.title, :length => truncate_length), { :controller => 'articles', :action => 'show', :id => article.id, :project_id => @project}, :title => article.title %>
    5:     <%= format_article_summary(article, summary_format, :truncate => truncate_length ) %>
    6:   </div>	
    7: <% end %>
  lib/redmine/i18n.rb:30:in `l'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Processing by UsErrorsController#error_500 as HTML
  Parameters: {"project_id"=>"reshenie_office"}
  Current user: barabanov (id=45)
  Rendered plugins/usability/app/views/errors/error_status.html.erb (2.4ms)
Completed 500 Internal Server Error in 5ms (Views: 2.5ms | ActiveRecord: 0.4ms)
```

**Comment by kostyfisik** [comment]
Did you checked to switch into English to reproduce the error? Which plug-in and redmine version you are using?

**Comment by kostyfisik** [comment]
It seems to work fine for our setup with russian too.  Environment:
  Redmine version                3.2.0.stable.15148
  Ruby version                   2.1.2-p95 (2014-05-08) [x86_64-linux]
  Rails version                  4.2.5.1
  Environment                    production
  Database adapter               Mysql2 

Started GET "/projects/test2sdfas/knowledgebase/articles" for 10.0.0.5 at 2016-02-16 23:23:11 +0300
Processing by ArticlesController#index as HTML
  Parameters: {"project_id"=>"test2sdfas"}
  Current user: k.ladutenko (id=8)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_jump_box.html.erb (3.1ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/_list.html.erb (2.5ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/_list.html.erb (2.1ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/_list.html.erb (3.1ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (2.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (5.4ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree.html.erb (6.4ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/index.html.erb within layouts/base (33.1ms)
  Rendered inline template (0.7ms)
  Rendered plugins/redmine_wiki_extensions/app/views/wiki_extensions/_html_header.html.erb (1.1ms)
  Rendered plugins/redmine_favourite_projects/app/views/favourite_projects/_favourite_projects_searchbox_partial.html.erb (0.1ms)
  Rendered plugins/redmine_favourite_projects/app/views/favourite_projects/_update_menu.erb (0.1ms)
  Rendered plugins/redmine_wiki_extensions/app/views/wiki_extensions/_body_bottom.html.erb (0.3ms)
Completed 200 OK in 109ms (Views: 74.0ms | ActiveRecord: 10.8ms)
![screenshot from 2016-02-16 23-27-31](https://cloud.githubusercontent.com/assets/5239997/13090098/e4991402-d504-11e5-803e-ce80bfca5290.png)

**Comment by barbiedrummer** [comment]
Hi, Konstantin.

Sorry for delay. There is NO issue when language is switched in English.

Environment:
  Redmine version                3.1.0.stable
  Ruby version                   2.2.0-p0 (2014-12-25) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            2.7.1
  Filesystem
Redmine plugins:
  a_common_libs                  2.1.0
  ajax_counters                  1.3.0
  extra_queries                  2.0.3
  redmine_checklists             3.1.3
  redmine_issue_templates        0.1.0
  redmine_knowledgebase          3.1.0
  redmine_tagging                0.1.3
  rm_user_mentions               1.0.0
  scrum                          0.13.1
  sidebar_hide                   0.0.7
  usability                      2.1.2

Text of issue:
translation data {:one=>"Рейтинг: %{rating_avg}/%{rating_max} после
одного голоса", :other=>"Рейтинг: %{rating_avg}/%{rating_max} после
%{count} голосов"} can not be used with :count => 0

Лог ошибки

        /usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/pluralization.rb:35:in
`pluralize'
/usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:40:in
`translate'
/usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/fallbacks.rb:45:in
`block (2 levels) in translate'
/usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/fallbacks.rb:44:in
`catch'
/usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/fallbacks.rb:44:in
`block in translate'
/usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/fallbacks.rb:42:in
`each'
/usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/fallbacks.rb:42:in
`translate'
/usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:158:in
`block in translate'
/usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:154:in `catch'
/usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:154:in `translate'
/opt/redmine/lib/redmine/i18n.rb:30:in `l'
/opt/redmine/plugins/usability/lib/usability/i18n_patch.rb:17:in
`l_with_usability'
/opt/redmine/plugins/redmine_knowledgebase/app/helpers/knowledgebase_helper.rb:22:in
`format_article_summary'
/opt/redmine/plugins/redmine_knowledgebase/app/views/articles/_list.html.erb:5:in
`block in _plugins_redmine_knowledgebase_app_views_articles__list_html_erb___3456023713650143003_70209722291600'
/opt/redmine/plugins/redmine_knowledgebase/app/views/articles/_list.html.erb:1:in
`each'
/opt/redmine/plugins/redmine_knowledgebase/app/views/articles/_list.html.erb:1:in
`_plugins_redmine_knowledgebase_app_views_articles__list_html_erb___3456023713650143003_70209722291600'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:145:in
`block in render'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in
`instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:333:in
`instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:143:in
`render'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/partial_renderer.rb:339:in
`render_partial'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/partial_renderer.rb:310:in
`block in render'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in
`block in instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in
`block in instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in
`instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in
`instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in
`instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/partial_renderer.rb:309:in
`render'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:47:in
`render_partial'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:21:in
`render'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/helpers/rendering_helper.rb:32:in
`render'
/opt/redmine/plugins/redmine_knowledgebase/app/views/articles/index.html.erb:51:in
`_plugins_redmine_knowledgebase_app_views_articles_index_html_erb___4315088799852819395_70209722602360'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:145:in
`block in render'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in
`instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:333:in
`instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:143:in
`render'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:54:in
`block (2 levels) in render_template'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in
`block in instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in
`block in instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in
`instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in
`instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in
`instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:53:in
`block in render_template'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:61:in
`render_with_layout'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:52:in
`render_template'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:14:in
`render'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:42:in
`render_template'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:23:in
`render'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:100:in
`_render_template'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/streaming.rb:217:in
`_render_template'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:83:in
`render_to_body'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:32:in
`render_to_body'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/renderers.rb:37:in
`render_to_body'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/rendering.rb:25:in
`render'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:16:in
`render'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in
`block (2 levels) in render'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in
`block in ms'
/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in
`ms'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in
`block in render'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:87:in
`cleanup_view_runtime'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:25:in
`cleanup_view_runtime'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:43:in
`render'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:10:in
`default_render'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:5:in
`send_action'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in
`process_action'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in
`process_action'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in
`block in process_action'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in
`block (2 levels) in compile'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:496:in
`block (2 levels) in around'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:311:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:311:in
`block (2 levels) in halting'
/opt/redmine/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430:in
`block in make_lambda'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:310:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:310:in
`block in halting'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:495:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:495:in
`block in around'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in
`run_callbacks'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in
`process_action'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in
`process_action'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in
`block in process_action'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in
`block in instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in
`instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in
`instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in
`process_action'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in
`process_action'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in
`process_action'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in
`process'
/usr/local/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in
`process'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in
`dispatch'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in
`dispatch'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in
`block in action'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in
`dispatch'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in
`serve'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in
`block in serve'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in
`each'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in
`serve'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in
`context'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in
`block in call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in
`run_callbacks'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in
`call_app'
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in
`block in call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in
`block in tagged'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in
`tagged'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in
`tagged'
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in
`call'
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in
`public_send'
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in
`method_missing'
/usr/local/lib/ruby/gems/2.2.0/gems/passenger-5.0.14/lib/phusion_passenger/rack/thread_handler_extension.rb:94:in
`process_request'
/usr/local/lib/ruby/gems/2.2.0/gems/passenger-5.0.14/lib/phusion_passenger/request_handler/thread_handler.rb:149:in
`accept_and_process_next_request'
/usr/local/lib/ruby/gems/2.2.0/gems/passenger-5.0.14/lib/phusion_passenger/request_handler/thread_handler.rb:110:in
`main_loop'
/usr/local/lib/ruby/gems/2.2.0/gems/passenger-5.0.14/lib/phusion_passenger/request_handler.rb:415:in
`block (3 levels) in start_threads'
/usr/local/lib/ruby/gems/2.2.0/gems/passenger-5.0.14/lib/phusion_passenger/utils.rb:111:in
`block in create_thread_and_abort_on_exception'
--
С уважением,
Алексей Барабанов.


2016-02-16 23:29 GMT+03:00 Konstantin Ladutenko <notifications@github.com>:

**Comment by kostyfisik** [comment]
There is no issue for me in Russian . You can
1) Check the encoding of config/locale/ru.yml in the plugin dir. It should be utf8 (I suppose)
2) Try to update redmine 3.2. This will give you a bonus of much better experience on mobile devices. 
3) Force using English for the plugin (just delete config/locale/ru.yml )

**Comment by kostyfisik** [comment]
By the way you can also try to use https://github.com/robspearman/redmine_knowledgebase fork, which seems to be quite a bit ahead of original alexbevi code (16 commits with several bugfixes at the moment...)

**Comment by barbiedrummer** [comment]
Thanks for your advice.

I've found the solution.

I've just added line to ru.yml:
>    zero: "Голосов нет"
after:
>   label_summary_toprated_articles:
>    one: "Рейтинг: %{rating_avg}/%{rating_max} после одного голоса"
>    other: "Рейтинг: %{rating_avg}/%{rating_max} после %{count} голосов"


--
С уважением,
Алексей Барабанов.

2016-02-19 14:41 GMT+03:00 Konstantin Ladutenko <notifications@github.com>:

**Comment by kostyfisik** [comment]
Could you provide a pull request with a fix? Here, or probably to robspearman fork?
