### ISSUE TITLE
incorrect "label_kb_link" in ko.yml

### ISSUE THREAD

**Issue by smanioso** [alexbevi/redmine_knowledgebase#321]
There is an error in "config'/locales/ko.yml"

Current value of "label_kb_link" is  "KB#{{kb_id}}". But, in my opinion, it should be "KB#%{kb_id}".

After modifying, macros about articles works well.

**Comment by alexbevi** [comment]
@smanioso there are a number of outstanding translations for the [ko locale](https://github.com/alexbevi/redmine_knowledgebase/blob/master/config/locales/ko.yml). If you can fill in any blanks or fix anything that seems wrong, it would be much appreciated ;)

**Comment by smanioso** [comment]
@alexbevi Okay, I will. But it can take a while to finish because there are many things to finish until next week.

**Comment by alexbevi** [comment]
@smanioso not sure if you think you'd have a chance to update these translations. If not, I'll just close this issue.
