### ISSUE TITLE
Error installing gem

### ISSUE THREAD

**Issue by drdelportillo** [alexbevi/redmine_knowledgebase#322]
Hello

when I run the rake command to install gems you ask me and asks me to run the install command bundle I do and I get the folowing mistake

I use the version 3.0.1

attached error in the console

![sin titulo](https://cloud.githubusercontent.com/assets/15143987/13890730/c75888ac-ed2b-11e5-993b-48ea713abcb5.png)

**Comment by alexbevi** [comment]
@drdelportillo have a look at https://github.com/alexbevi/redmine_knowledgebase/blob/master/Gemfile. Just copy/paste this to your Gemfile and try running again.

**Comment by drdelportillo** [comment]
hi thanks for reply

In the Gemfile what I have and show me the error I get is the same of the attached image is as if the served where this gem was not accessible

I use version 3.0.1 redmine bitnami

**Comment by alexbevi** [comment]
@drdelportillo what if you changed the line to

`gem 'redmine_acts_as_taggable_on', git: "https://github.com/alexbevi/redmine_acts_as_taggable_on.git"`

**Comment by drdelportillo** [comment]
gem 'redmine_acts_as_taggable_on', :git => "https://github.com/alexbevi/redmine_acts_as_taggable_on"

I find this and its work 

thanks.
