### ISSUE TITLE
the article cannot use the image created by [Clipboard image paste]

### ISSUE THREAD

**Issue by archonwang** [alexbevi/redmine_knowledgebase#325]
any solution? thanks so much. I used redmine 3.2.X

**Comment by alexbevi** [comment]
@archonwang can you try this with the v3.2.0 release and let me know if the issue persists?

**Comment by archonwang** [comment]
@alexbevi ,  I will test it later. Thanks.

**Comment by archonwang** [comment]
it's OK now. Thanks so much.

**Comment by tiurlumbangaol** [comment]
the problem may occur because of issue #383
