### ISSUE TITLE
"Internal error" when creating an article

### ISSUE THREAD

**Issue by nickfaarvang** [alexbevi/redmine_knowledgebase#326]
Whenever I create an article I get the following error:

"Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error."

I can create categories and sub-categories just fine. I have not been able to find a similar issue described anywhere.

Environment:
  Redmine version                3.0.3.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem  
Redmine plugins:
  a_common_libs                  2.1.7
  contracts                      2.1.0
  redcase                        1.0
  redmine_ckeditor               1.1.3
  redmine_contacts               4.0.3
  redmine_default_members        1.0-devel
  redmine_documents_short        0.3.0
  redmine_issue_tabs             1.1.1
  redmine_knowledgebase          3.1.0
  redmine_wktime                 2.0
  time_logger                    0.5.3

**Comment by nickfaarvang** [comment]
Fatal error in the log file:
I, [2016-05-23T13:37:12.369254 #7568]  INFO -- : Completed 200 OK in 275ms (Views: 217.4ms | ActiveRecord: 8.9ms)
I, [2016-05-23T13:37:30.492055 #7568]  INFO -- : Started POST "/projects/lounge-aarhus/knowledgebase/articles" for 192.168.40.221 at 2016-05-23 13:37:30 +020
I, [2016-05-23T13:37:30.495806 #7568]  INFO -- : Processing by ArticlesController#create as HTML
I, [2016-05-23T13:37:30.496052 #7568]  INFO -- :   Parameters: {"utf8"=>"â..", "authenticity_token"=>"GzRFhiPCYO/SQzvQeMJ+OQt0l7RGYfGBqt/40jR0Ce9S2ziwaCdagCu
I, [2016-05-23T13:37:30.505631 #7568]  INFO -- :   Current user: nick.f (id=7)
E, [2016-05-23T13:37:30.588806 #7568] ERROR -- : Mysql2::Error: Unknown column 'taggings.context' in 'where clause': SELECT `tags`.* FROM `tags` INNER JOIN `
I, [2016-05-23T13:37:30.761944 #7568]  INFO -- : Completed 500 Internal Server Error in 266ms (ActiveRecord: 174.3ms)
F, [2016-05-23T13:37:30.770261 #7568] FATAL -- :
ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'taggings.context' in 'where clause': SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tag
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
  activerecord (4.2.1) lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
  activerecord (4.2.1) lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `exec_query'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:347:in `select'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'

**Comment by alexbevi** [comment]
@nickfaarvang I'm assuming you installed the redmine_contacts plugin first, as this also includes a tagging library. I'm looking into better way of handling this as it's a recurring issue...

**Comment by mathiaswallgren** [comment]
@alexbevi I am having this same issue and I also have the CRM light contacts plugin installed.
Is this issue resolved by uninstalling the contacts plugin and then re-install the knowledgebase plugin?
Are there any other workarounds?
