### ISSUE TITLE
FEATURE: Include knowledgebase content when copying a project

### ISSUE THREAD

**Issue by thomaskor** [alexbevi/redmine_knowledgebase#327]
Hi,
If i copy an project from my project-template then the knowledgebase in new project is empty.
What am I doing wrong or is not a feature?
Thanks and Greetings
Thomas

**Comment by alexbevi** [comment]
@thomaskor I would need to implement the `:model_project_copy_before_save` hook in order to have knowledgebase content copied.

We'd need to define what should be copied (assuming categories), but others may have other ideas. Might as well get a discussion going ;)
