### ISSUE TITLE
Better redmine text editor integration?

### ISSUE THREAD

**Issue by freerider75** [alexbevi/redmine_knowledgebase#340]
Hi,
I'm using the  [image clipboard paste](https://www.redmine.org/plugins/redmine_image_clipboard_paste) plugin, which allows to put images from clipboard right into the text without saving and uploading them before, but it doesn't seem to work with the KB Plugin, though it would be very useful, as I prefer to write more KB's rather than wiki pages.

Actually, I don't know if this problem is due to the KB plugin or if it depends on how the clipboard paste plugin is written.

Thank you.

**Comment by alexbevi** [comment]
@freerider75 if you switch to https://github.com/peclik/clipboard_image_paste instead, he's already build support in for clipboard paste into knowledgebase articles. If you want to use the other clipboard paste plugin, you'd need to ask the author if he wants to support this plugin.

**Comment by tiurlumbangaol** [comment]
the problem may occurs because of issue #383
