### ISSUE TITLE
NameError: uninitialized constant KnowledgebaseLinkHelper

### ISSUE THREAD

**Issue by jcagentzero** [alexbevi/redmine_knowledgebase#341]
Hi, I've been trying to install any plugin in Redmine 3.2.1 for several days now and I keep on failing due to several reasons. When I solve one, another will arise. This is the latest error I encountered and this is my setup:

> Environment:
  Redmine version                3.2.1.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  no plugin installed

This is the full stack trace of the error:

> ** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant KnowledgebaseLinkHelper
/usr/share/redmine/lib/plugins/redmine_knowledgebase/lib/macros.rb:1:in `<top (required)>'
/usr/share/redmine/lib/plugins/redmine_knowledgebase/init.rb:10:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:446:in `instance_exec'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:192:in `block in simple'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `block in call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `each'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/lib/ruby/vendor_ruby/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
/usr/lib/ruby/vendor_ruby/rails/application.rb:352:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rails/application.rb:328:in `require_environment!'
/usr/lib/ruby/vendor_ruby/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:165:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:150:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:115:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:100:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:78:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
bin/rake:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

I am also curious why the plugins are inside <redmine installation folder>/lib/plugins/ while others are inside  <redmine installation folder>/plugins/ or  <redmine installation folder>/vendor. Thanks in advance.

**Comment by alexbevi** [comment]
@jcagentzero i'm not really sure how you've installed this. I would recommend you take a step back, read some of the installation guides (or docs on redmine.org) and try again.

Maybe try this:

1. re-download redmine and extract
2. run the database setup and migrations, and install the default data (see docs)
3. grab a plugin and put in in the ./plugins dir
4. run the plugin migrations

It sounds like this is just an installation that's gone sideways. I'm going to close this issue as it doesn't sound specific to the plugin, but hopefully i helped a bit with the above.
