### ISSUE TITLE
Table viewings not created

### ISSUE THREAD

**Issue by pousterlus** [alexbevi/redmine_knowledgebase#342]
Hello,

First, thank you for letting everyone benefits from your work.
I've just tried to install your plugin. I read that tagging system is a nightmare for you to handle because of some already installed plugins like Redmine CRM.

I don't know if it's related, but this is what I get when I try to create a new article (categories are created just fine) : 

```
Completed 200 OK in 1694ms (Views: 0.3ms | ActiveRecord: 7.8ms)
Started GET "/projects/base-de-co/knowledgebase/articles/6" for 195.132.xxx.xxx at 2017-05-13 17:50:34 +0200
Processing by ArticlesController#show as HTML
  Parameters: {"project_id"=>"kb", "id"=>"6"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 11ms (ActiveRecord: 6.1ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'redmine.viewings' doesn't exist: SHOW FULL FIELDS FROM `viewings`):
  plugins/redmine_knowledgebase/lib/acts_as_viewed.rb:179:in `viewed_by?'
  plugins/redmine_knowledgebase/lib/acts_as_viewed.rb:157:in `block in view'
  plugins/redmine_knowledgebase/lib/acts_as_viewed.rb:156:in `view'
  plugins/redmine_knowledgebase/app/controllers/articles_controller.rb:88:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Is it the same problem here ?

Thanks, and regards.

-- 
Léo.

**Comment by alexbevi** [comment]
@pousterlus it's complaining that the `viewings` table doesn't exist. It looks like you didn't run the plugin migrations
