### ISSUE TITLE
Index name 'index_taggings_on_tag_id' on table 'taggings' does not exist

### ISSUE THREAD

**Issue by Saylrman64** [alexbevi/redmine_knowledgebase#344]
Hello,

I'm trying to evaluate this plugin as it looks like it would be of great use and much better than simple wikis but I cannot get it installed.

Initially I ran into the conflicts that other have where the existing tags and taggable tables from plugins like Redmine CRM, Questions, or People caused problems so I simply removed them in hope I could just get the plugin installed and tested.

Even then when I run the rake redmine:plugins:migrate NAME=redmine_knowledgebase
I get:
sql2::Error: Table 'Development.tags' doesn't exist: CREATE UNIQUE INDEX `index_tags_on_name`  ON `tags` (`name`)

This gives me the impression the plugin now relies on the tags table but if no other plugin requires it, why wouldn't this plugin create it?

So I used the code suggested by pinpikokun in https://github.com/alexbevi/redmine_knowledgebase/issues/320 to create the tables.

Now the error is Index name 'index_taggings_on_tag_id' on table 'taggings' does not exist
And if I create the unique index I get the error: Index name 'index_taggings_on_tag_id' on table 'taggings' already exist

Now I'm in the same cycle all the others are with conflicts with tags and tagging tables.

Is this plugin being maintained or should I look elsewhere for a robust article solution?
Any help would be appreciated.

Thanks
============================
Environment:
  Redmine version                3.3.3.stable.16543
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  progressive_projects_list      3.0.1
  recurring_tasks                2.0.0-pre
  redmine_agile                  1.4.3
  redmine_better_gantt_chart     0.9.0
  redmine_blocks_layout          0.0.2
  redmine_checklists             3.1.5
  redmine_dmsf                   1.5.9
  redmine_ics_export             3.0.1.dev
  redmine_issue_templates        0.1.5
  redmine_lightbox2              0.3.2
  redmine_monitoring_controlling 0.1.1
  redmine_sidebar_toc_pt         1.7.0
  redmine_spent_time             3.1.2
  redmine_spent_time_in_issue_description 2.8.0
  redmine_tab                    0.4.0
  redmine_touch                  0.0.3
  redmine_tweaks                 1.0.2
  redmine_zenedit                0.0.2
  sidebar_hide                   0.0.8
  timelog_timer                  2.0.0
  unread_issues                  2.1.1
  wiking                         1.0.0b

**Comment by Sabrimjd** [comment]
Hi any news ? got the same issue
