### ISSUE TITLE
PG::UndefinedTable: ERROR: no existe la relación «kb_categories» 

### ISSUE THREAD

**Issue by gustavalentin** [alexbevi/redmine_knowledgebase#345]
Hello everyone. I install plugin in redmine but it gives me the following error

Redmine. Error 500

Global error
PG::UndefinedTable: ERROR: no existe la relación «kb_categories» LINE 5: WHERE a.attrelid = '"kb_categories"'::regclas... ^ : SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum WHERE a.attrelid = '"kb_categories"'::regclass AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum 

Back  

Error log

        /opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/schema_cache.rb:49:in `columns_hash'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/association_scope.rb:85:in `column_for'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/association_scope.rb:94:in `bind'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/association_scope.rb:103:in `last_chain_scope'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/association_scope.rb:139:in `add_constraints'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/association_scope.rb:39:in `scope'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/association_scope.rb:5:in `scope'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/association.rb:97:in `association_scope'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/association.rb:86:in `scope'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:423:in `scope'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/collection_proxy.rb:37:in `initialize'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:106:in `new'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:106:in `create'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:41:in `reader'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/builder/association.rb:115:in `categories'
/opt/redmine/plugins/redmine_knowledgebase/app/controllers/articles_controller.rb:22:in `index'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:237:in `block in action'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/rack-1.6.1/lib/rack/etag.rb:24:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/rack-1.6.1/lib/rack/conditionalget.rb:25:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/rack-1.6.1/lib/rack/head.rb:13:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/rack-1.6.1/lib/rack/session/abstract/id.rb:225:in `context'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/rack-1.6.1/lib/rack/session/abstract/id.rb:220:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/query_cache.rb:36:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/rack-1.6.1/lib/rack/methodoverride.rb:22:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/rack-1.6.1/lib/rack/runtime.rb:18:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/rack-1.6.1/lib/rack/sendfile.rb:113:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `public_send'
/opt/redmine/vendor/cache/ruby/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `method_missing'
/usr/local/rvm/gems/ruby-2.2.1/gems/passenger-5.0.8/lib/phusion_passenger/rack/thread_handler_extension.rb:89:in `process_request'
/usr/local/rvm/gems/ruby-2.2.1/gems/passenger-5.0.8/lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/local/rvm/gems/ruby-2.2.1/gems/passenger-5.0.8/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/local/rvm/gems/ruby-2.2.1/gems/passenger-5.0.8/lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
/usr/local/rvm/gems/ruby-2.2.1/gems/passenger-5.0.8/lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'

thanks.!!!!"

**Comment by ace280** [comment]
Did rake redmine:plugins:migrate NAME=redmine_knowledgebase come out without errors?
