### ISSUE TITLE
Files not display when added

### ISSUE THREAD

**Issue by jgarneau** [alexbevi/redmine_knowledgebase#351]
Using Redmine 3.4.4, adding a file, the file name is not displayed in the files tab.

**Comment by tgoshima** [comment]
It is the same in my Redmine 3.4.4 environment.

**Comment by gzuffo** [comment]
Hello, I have the same issue  here.
It looses the reference, the upload is made,  the server receives the file, but, the article did not get the links.
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.5
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  easy_gantt                     1.10
  easy_instant_messages          2016
  easy_mindmup                   1.0
  easy_wbs                       1.5
  redmine_agile                  1.4.4
  redmine_checklists             3.1.10
  redmine_knowledgebase          3.3.1
  redmine_rouge_highlighter      0.0.1
  redmine_wiki_extensions        0.8.1
  redmine_workload               1.1.0
  redmineup_tags                 2.0.1

**Comment by seraph3000** [comment]
I am using Redmine 3.4.4 and knowledgebase 3.3.1. Perhaps, the "knowledgebase" plugin /plugins/redmine_knowledgebase/app/views/attachments/_links.html.erb works until Redmine 3.3, but since Redmine 3.4 the specification has changed, so _links.html.erb Does not it work as an attached file processing? I thought, and deleted or moved _links.html.erb on the plugin side, it worked.

**Comment by gzuffo** [comment]
seraph3000 , it has been worked! thanks man!

**Comment by r3code** [comment]
**The symptoms of this problem:**
When you edit an the knowledgebase article you see a block named "Attachments" but it looks like there some empty lines inside. So it this case files are really attached and saved to the server, but the block has been rendered wrong.
@seraph3000 Thanks a lot. I 've experienced  same problem with Bitnami Stack / Redmine 3.4.5.stable
I find a file `_links.html.erb` in a folder ` /redmine_knowledgebase/app/views/attachments` and then renamed it to `_links.html.erb.bak` (you can delete it). Restarted the Redmine and ISSUE has been fixed!

**Comment by alexbevi** [comment]
Closed via #406
