### ISSUE TITLE
Redmine 4.x Rails 5.2 support

### ISSUE THREAD

**Issue by ssrini** [alexbevi/redmine_knowledgebase#368]
The plugin cannot be used with Redmine 4.x due to the upgrade to Rails 5.2.

One specific issue was this: 
`The application encountered the following error: undefined method type_cast_for_database for class ActiveRecord::ConnectionAdapters::Column (NameError)`

The relevant line from articles_controller.rb: 
`ActiveRecord::ConnectionAdapters::Column.send(:alias_method, :type_cast, :type_cast_for_database)`

Any chance if this plugin will be upgraded to support Redmine 4.x?

**Comment by funk-yourself** [comment]
You can try [this](https://github.com/centosadmin/redmine_knowledgebase) fork

**Comment by srinisubramanian** [comment]
Thanks.  This worked perfectly.

**Comment by ssrini** [comment]
Thanks.  This worked perfectly.
