### ISSUE TITLE
Redmine 4.1.1 compatibility

### ISSUE THREAD

**Issue by reshetov** [alexbevi/redmine_knowledgebase#371]
I added compatibility with Redmine 4.1.1 for this plugin. Be glad if it will be useful
https://github.com/reshetov/redmine_knowledgebase

**Comment by robspearman** [comment]
Thanks for your efforts Andrew!  Look like a lot of changes.  Can you 
make a pull request and we can discuss there?

**Comment by reshetov** [comment]
Sure. I created PR https://github.com/alexbevi/redmine_knowledgebase/pull/372
