### ISSUE TITLE
error installing ubuntu 18.04 redmine 4.1.1.

### ISSUE THREAD

**Issue by ghost** [alexbevi/redmine_knowledgebase#375]
i am trying to install this on my ubuntu 18.04 server. when running the following command: 
rake redmine:plugins:migrate NAME=redmine_knowledgebase

it fails in my error logs i see the following 

root@ip-172-31-26-138:/var/www/html/redmine# rake redmine:plugins:migrate NAME=redmine_knowledgebase
rake aborted!
ActiveRecord::NoDatabaseError: Unknown database 'redmine_development'

--------
here is the error log

[ E 2020-06-30 13:24:48.8904 900/T1a age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/www/html/redmine: The application encountered the following error: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class ActsAsTaggableOnMigration < ActiveRecord::Migration[4.2] (StandardError)
  Error ID: 10bc942f
  Error details saved to: /tmp/passenger-error-ubhGv3.html

[ E 2020-06-30 14:17:15.4852 900/T9 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-82] Cannot checkout session because a spawning error occurred. The identifier of the error is f990480a. Please see earlier logs for details about the error.

any help would be appreciated.

**Comment by robspearman** [comment]
Redmine 4.1.1 support was only merged in today, so try now.

**Comment by Heroldgray** [comment]
> i am trying to install this on my ubuntu 18.04 server. when running the following command:
> rake redmine:plugins:migrate NAME=redmine_knowledgebase
> it fails
 
Anybody succeed with last version merge with added  4.1.1 support ?

**Comment by joachim717** [comment]
Hi, unfortunately not
Mysql2::Error::ConnectionError: Access denied for user 'bn_redmine'@'%' to database 'bitnami_redmine_development'
/opt/bitnami/redmine/plugins/additionals/init.rb:44:in `<top (required)>'
/opt/bitnami/redmine/lib/redmine/plugin.rb:181:in `block in load'
/opt/bitnami/redmine/lib/redmine/plugin.rb:172:in `each'
/opt/bitnami/redmine/lib/redmine/plugin.rb:172:in `load'
/opt/bitnami/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/opt/bitnami/redmine/config/environment.rb:16:in `<top (required)>'

Best
Joachim

**Comment by ayesjm** [comment]
i am still getting a rake error:
rake aborted!
ActiveRecord::AdapterNotSpecified: 'development' database is not configured. Available: ["production"]
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/connection_specification.rb:260:in `resolve_symbol_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/connection_specification.rb:241:in `resolve_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/connection_specification.rb:143:in `resolve'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/connection_handling.rb:57:in `establish_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/railtie.rb:136:in `block (2 levels) in <class:Railtie>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:42:in `each'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/railtie.rb:132:in `block in <class:Railtie>'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
/var/www/html/redmine/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
/var/lib/gems/2.5.0/gems/railties-5.2.4.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/lib/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
root@ip-172-31-98-138:/var/www/html/redmine# nano /var/lib/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/connection_specification.rb

**Comment by robspearman** [comment]
The error implies that you need to specify 'production' in your migration command.

**Comment by ayesjm** [comment]
i'm running redmine:plugins:migrate NAME=redmine_knowledgebase. how do i specify production in the migration command?

**Comment by kingkins** [comment]
> Hi, unfortunately not
> Mysql2::Error::ConnectionError: Access denied for user 'bn_redmine'@'%' to database 'bitnami_redmine_development'
> /opt/bitnami/redmine/plugins/additionals/init.rb:44:in `<top (required)>' /opt/bitnami/redmine/lib/redmine/plugin.rb:181:in `block in load'
> /opt/bitnami/redmine/lib/redmine/plugin.rb:172:in `each' /opt/bitnami/redmine/lib/redmine/plugin.rb:172:in `load'
> /opt/bitnami/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>' /opt/bitnami/redmine/config/environment.rb:16:in `<top (required)>'
> 
> Best
> Joachim

You need modify "redmine\htdocs\config\database.yml"
Add your db password of developer env in this file!

or try to this cmd:
bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_knowledgebase

The point is assign production RAILS_ENV.(Default is developer env but Bitnami Redmine set null password.)
