### ISSUE TITLE
Description on redmine.org is deprecated

### ISSUE THREAD

**Issue by ace280** [alexbevi/redmine_knowledgebase#381]
The description at https://www.redmine.org/plugins/redmine_knowledgebase is deprecated. 

It states that redmine_knowledgebase is compatible up until 3.2.x,. This might lead to users ignoring this great plugin that is, in fact, compatible up to 4.1.x.

You might also add a redirect to redmine.org in readmine.md just for completion.

Thank you for the great work and best regards,

ace28

**Comment by alexbevi** [comment]
This should be addressed by #411, so I've bumped the version to 5.0 and updated redmine.org
