### ISSUE TITLE
Plugin redmine_konwedgebase was not found.

### ISSUE THREAD

**Issue by zl6536** [alexbevi/redmine_knowledgebase#384]
OS:centos 7.2
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.5.8-p224 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.14.0
  Git                            2.27.0
  Filesystem                     
Redmine plugins:
  redmine_image_clipboard_paste  3.3.0
### running error
[root@redmine plugins]# /opt/redmine-4.1.1-3/ruby/bin/rake redmine:plugins:migrate NAME=redmine_konwedgebase
(in /opt/redmine-4.1.1-3/apps/redmine/htdocs)
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/file_utils.rb:10: warning: already initialized constant FileUtils::RUBY
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/file_utils.rb:10: warning: previous definition of RUBY was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/file_utils.rb:108: warning: already initialized constant FileUtils::LN_SUPPORTED
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/file_utils.rb:108: warning: previous definition of LN_SUPPORTED was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/file_utils_ext.rb:17: warning: already initialized constant Rake::FileUtilsExt::DEFAULT
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/file_utils_ext.rb:17: warning: previous definition of DEFAULT was here
WARNING: Possible conflict with Rake extension: String#ext already exists
WARNING: Possible conflict with Rake extension: String#pathmap already exists
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:44: warning: already initialized constant Rake::FileList::ARRAY_METHODS
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:44: warning: previous definition of ARRAY_METHODS was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:47: warning: already initialized constant Rake::FileList::MUST_DEFINE
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:47: warning: previous definition of MUST_DEFINE was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:51: warning: already initialized constant Rake::FileList::MUST_NOT_DEFINE
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:51: warning: previous definition of MUST_NOT_DEFINE was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:55: warning: already initialized constant Rake::FileList::SPECIAL_RETURN
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:55: warning: previous definition of SPECIAL_RETURN was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:61: warning: already initialized constant Rake::FileList::DELEGATING_METHODS
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:61: warning: previous definition of DELEGATING_METHODS was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:86: warning: already initialized constant Rake::FileList::GLOB_PATTERN
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:86: warning: previous definition of GLOB_PATTERN was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:381: warning: already initialized constant Rake::FileList::DEFAULT_IGNORE_PATTERNS
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:381: warning: previous definition of DEFAULT_IGNORE_PATTERNS was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:387: warning: already initialized constant Rake::FileList::DEFAULT_IGNORE_PROCS
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/file_list.rb:387: warning: previous definition of DEFAULT_IGNORE_PROCS was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/version.rb:3: warning: already initialized constant Rake::VERSION
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/version.rb:3: warning: previous definition of VERSION was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/version.rb:6: warning: already initialized constant Rake::Version::MAJOR
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/version.rb:6: warning: previous definition of MAJOR was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/version.rb:6: warning: already initialized constant Rake::Version::MINOR
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/version.rb:6: warning: previous definition of MINOR was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/version.rb:6: warning: already initialized constant Rake::Version::BUILD
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/version.rb:6: warning: previous definition of BUILD was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/version.rb:6: warning: already initialized constant Rake::Version::OTHER
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/version.rb:6: warning: previous definition of OTHER was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/version.rb:8: warning: already initialized constant Rake::Version::NUMBERS
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/version.rb:8: warning: previous definition of NUMBERS was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/linked_list.rb:110: warning: already initialized constant Rake::LinkedList::EMPTY
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/linked_list.rb:110: warning: previous definition of EMPTY was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/scope.rb:41: warning: already initialized constant Rake::Scope::EMPTY
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/scope.rb:41: warning: previous definition of EMPTY was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/promise.rb:12: warning: already initialized constant Rake::Promise::NOT_SET
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/promise.rb:12: warning: previous definition of NOT_SET was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:13: warning: already initialized constant Rake::CommandLineOptionError
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:13: warning: previous definition of CommandLineOptionError was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:41: warning: already initialized constant Rake::Application::DEFAULT_RAKEFILES
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:41: warning: previous definition of DEFAULT_RAKEFILES was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/task_arguments.rb:108: warning: already initialized constant Rake::EMPTY_TASK_ARGS
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task_arguments.rb:108: warning: previous definition of EMPTY_TASK_ARGS was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/invocation_chain.rb:55: warning: already initialized constant Rake::InvocationChain::EMPTY
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/invocation_chain.rb:55: warning: previous definition of EMPTY was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/early_time.rb:21: warning: already initialized constant Rake::EARLY
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/early_time.rb:21: warning: previous definition of EARLY was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/late_time.rb:17: warning: already initialized constant Rake::LATE
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/late_time.rb:17: warning: previous definition of LATE was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/backtrace.rb:4: warning: already initialized constant Rake::Backtrace::SYS_KEYS
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/backtrace.rb:4: warning: previous definition of SYS_KEYS was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/backtrace.rb:5: warning: already initialized constant Rake::Backtrace::SYS_PATHS
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/backtrace.rb:5: warning: previous definition of SYS_PATHS was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/backtrace.rb:8: warning: already initialized constant Rake::Backtrace::SUPPRESSED_PATHS
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/backtrace.rb:8: warning: previous definition of SUPPRESSED_PATHS was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/backtrace.rb:12: warning: already initialized constant Rake::Backtrace::SUPPRESSED_PATHS_RE
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/backtrace.rb:12: warning: previous definition of SUPPRESSED_PATHS_RE was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/backtrace.rb:16: warning: already initialized constant Rake::Backtrace::SUPPRESS_PATTERN
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/backtrace.rb:16: warning: previous definition of SUPPRESS_PATTERN was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake.rb:70: warning: already initialized constant FileList
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake.rb:70: warning: previous definition of FileList was here
/opt/redmine-4.1.1-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake.rb:71: warning: already initialized constant RakeFileUtils
/opt/redmine-4.1.1-3/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake.rb:71: warning: previous definition of RakeFileUtils was here
Plugin redmine_konwedgebase was not found
please look up,help me!

**Comment by robspearman** [comment]
"konwedgebase" is not the correct name.
